name: kind_app
description: One Kind Message - Send and receive anonymous kind messages.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Navigation
  go_router: ^14.8.1

  # Supabase
  supabase_flutter: ^2.8.4

  # Environment
  flutter_dotenv: ^5.2.1

  # Typography
  google_fonts: ^6.2.1

  # Utils
  intl: ^0.19.0
  uuid: ^4.5.1
  shared_preferences: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.14
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true

  assets:
    - .env
