/// Constantes globales de l'application.
class AppConstants {
  AppConstants._();

  /// Nom de l'application.
  static const String appName = 'One Kind Message';

  /// Version de l'application.
  static const String appVersion = '1.0.0';

  /// Longueur maximale d'un message.
  static const int messageMaxLength = 200;

  /// Nombre d'éléments par page pour la pagination.
  static const int pageSize = 20;

  /// Timeout réseau en secondes.
  static const int networkTimeoutSeconds = 15;

  /// Phrases contemplatives pour l'écran d'accueil.
  static const List<String> contemplativePhrases = [
    'Un mot peut changer une journée.',
    'La bienveillance voyage en silence.',
    'Quelqu\'un, quelque part, a besoin de vos mots.',
    'Chaque message porte une lumière.',
    'Offrez un sourire invisible au monde.',
    'Votre douceur peut toucher un cœur.',
    // 'Un petit geste, un grand impact.',
    // 'Soyez la raison pour laquelle quelqu\'un sourit aujourd\'hui.',
    // 'La gentillesse est une langue que tout le monde comprend.',
    // 'Chaque mot compte. Choisissez-le avec soin.',
    // 'Le monde a besoin de plus de gentillesse. Commencez par un message.',
    // 'Votre message peut être le rayon de soleil dont quelqu\'un a besoin.',
    // 'La positivité est contagieuse. Partagez-la.',
    // 'Un simple mot peut illuminer la journée de quelqu\'un.',
    // 'Soyez le changement que vous voulez voir dans le monde.',
    // 'La gentillesse est un cadeau qui ne coûte rien mais vaut tout.',
    // 'Chaque message est une opportunité de faire une différence.',
    // 'Votre douceur peut toucher un cœur d\'une manière inattendue.',
    // 'Le monde est meilleur avec un peu plus de gentillesse.',
    // 'Un mot gentil peut changer le cours d\'une journée.',
    // 'Soyez la lumière dans la journée de quelqu\'un.',
    // 'La gentillesse est la plus belle forme de courage.',
    // 'Chaque message est une étincelle de positivité.',
    // 'Votre douceur peut être le baume dont quelqu\'un a besoin.',
    // 'Le monde a besoin de plus de sourires. Offrez-en un.',
    // 'Un mot gentil peut voyager loin et toucher des cœurs.',
    // 'Soyez la raison pour laquelle quelqu\'un croit en la gentillesse.',
    // 'La gentillesse est un langage universel.',
    // 'Chaque message est une opportunité de répandre la joie.',
    // 'Votre douceur peut être le soutien dont quelqu\'un a besoin.',
    // 'Le monde est plus beau avec un peu plus de lumière.',
    // 'Un mot gentil peut être le début d\'une belle journée.',
    // 'Soyez la raison pour laquelle quelqu\'un sourit aujourd\'hui.',
    // 'La gentillesse est un cadeau qui se multiplie.',
    // 'Chaque message est une vague de positivité.',
    // 'Votre douceur peut être le réconfort dont quelqu\'un a besoin.',
    // 'Le monde a besoin de plus de chaleur. Partagez-en.',
    // 'Un mot gentil peut être le pont entre deux cœurs.',
    // 'Soyez la raison pour laquelle quelqu\'un se sent spécial.',
    // 'La gentillesse est une force silencieuse mais puissante.',
    // 'Chaque message est une graine de bonheur.',
    // 'Votre douceur peut être la lumière dans l\'obscurité.',
    // 'Le monde est meilleur avec un peu plus de compassion.',
    // 'Un mot gentil peut être le début d\'une belle amitié.',
    // 'Soyez la raison pour laquelle quelqu\'un croit en la bonté.',
    // 'La gentillesse est un voyage, pas une destination.',
    // 'Chaque message est une opportunité de répandre l\'amour.',
    // 'Votre douceur peut être le soutien dont quelqu\'un a besoin.',
    // 'Le monde a besoin de plus de sourires. Offrez-en un.',
    // 'Un mot gentil peut voyager loin et toucher des cœurs.',
    // 'Soyez la raison pour laquelle quelqu\'un croit en la gentillesse.',
    // 'La gentillesse est un langage universel.',
    // 'Chaque message est une opportunité de répandre la joie.',
    // 'Votre douceur peut être le réconfort dont quelqu\'un a besoin.',
    // 'Le monde est plus beau avec un peu plus de lumière.',
    // 'Un mot gentil peut être le début d\'une belle journée.',
    // 'Soyez la raison pour laquelle quelqu\'un sourit aujourd\'hui.',
    // 'La gentillesse est un cadeau qui se multiplie.',
    // 'Chaque message est une vague de positivité.',
    // 'Votre douceur peut être le soutien dont quelqu\'un a besoin.',
    // 'Le monde a besoin de plus de chaleur. Partagez-en.',
    // 'Un mot gentil peut être le pont entre deux cœurs.',
    // 'Soyez la raison pour laquelle quelqu\'un se sent spécial.',
    // 'La gentillesse est une force silencieuse mais puissante.',
    // 'Chaque message est une graine de bonheur.',
    // 'Votre douceur peut être la lumière dans l\'obscurité.',
    // 'Le monde est meilleur avec un peu plus de compassion.',
    // 'Un mot gentil peut être le début d\'une belle amitié.',
    // 'Soyez la raison pour laquelle quelqu\'un croit en la bonté.',
    // 'La gentillesse est un voyage, pas une destination.',
    // 'Chaque message est une opportunité de répandre l\'amour.',
    // 'Votre douceur peut être le soutien dont quelqu\'un a besoin.',
    // 'Le monde a besoin de plus de sourires. Offrez-en un.',
    // 'Un mot gentil peut voyager loin et toucher des cœurs.',
    // 'Soyez la raison pour laquelle quelqu\'un croit en la gentillesse.',
    // 'La gentillesse est un langage universel.',
    // 'Chaque message est une opportunité de répandre la joie.',
    // 'Votre douceur peut être le réconfort dont quelqu\'un a besoin.',
    // 'Le monde est plus beau avec un peu plus de lumière.',
    // 'Un mot gentil peut être le début d\'une belle journée.',
    // 'Soyez la raison pour laquelle quelqu\'un sourit aujourd\'hui.',
    // 'La gentillesse est un cadeau qui se multiplie.',
    // 'Chaque message est une vague de positivité.',
    // 'Votre douceur peut être le soutien dont quelqu\'un a besoin.',
    // 'Le monde a besoin de plus de chaleur. Partagez-en.',
    // 'Un mot gentil peut être le pont entre deux cœurs.',
    // 'Soyez la raison pour laquelle quelqu\'un se sent spécial.',
    // 'La gentillesse est une force silencieuse mais puissante.',
    // 'Chaque message est une graine de bonheur.',
    // 'Votre douceur peut être la lumière dans l\'obscurité.',
    // 'Le monde est meilleur avec un peu plus de compassion.',
    // 'Un mot gentil peut être le début d\'une belle amitié.',
    // 'Soyez la raison pour laquelle quelqu\'un croit en la bonté.',
    // 'La gentillesse est un voyage, pas une destination.',
    // 'Chaque message est une opportunité de répandre l\'amour.',
    // 'Votre douceur peut être le soutien dont quelqu\'un a besoin.',
    // 'Le monde a besoin de plus de sourires. Offrez-en un.',
    // 'Un mot gentil peut voyager loin et toucher des cœurs.',
    // 'Soyez la raison pour laquelle quelqu\'un croit en la gentillesse.',
    // 'La gentillesse est un langage universel.',
    // 'Chaque message est une opportunité de répandre la joie.',
    // 'Votre douceur peut être le réconfort dont quelqu\'un a besoin.',
    // 'Le monde est plus beau avec un peu plus de lumière.',
    // 'Un mot gentil peut être le début d\'une belle journée.',
    // 'Soyez la raison pour laquelle quelqu\'un sourit aujourd\'hui.',
    // 'La gentillesse est un cadeau qui se multiplie.',
    // 'Chaque message est une vague de positivité.',
    // 'Votre douceur peut être le soutien dont quelqu\'un a besoin.',
    // 'Le monde a besoin de plus de chaleur. Partagez-en.',
    // 'Un mot gentil peut être le pont entre deux cœurs.',
    // 'Soyez la raison pour laquelle quelqu\'un se sent spécial.',
    // 'La gentillesse est une force silencieuse mais puissante.',
    // 'Chaque message est une graine de bonheur.',
    // 'Votre douceur peut être la lumière dans l\'obscurité.',
    // 'Le monde est meilleur avec un peu plus de compassion.',
    // 'Un mot gentil peut être le début d\'une belle amitié.',
    // 'Soyez la raison pour laquelle quelqu\'un croit en la bonté.',
    // 'La gentillesse est un voyage, pas une destination.',
    // 'Chaque message est une opportunité de répandre l\'amour.',
    // 'Votre douceur peut être le soutien dont quelqu\'un a besoin.',
    // 'Le monde a besoin de plus de sourires. Offrez-en un.',
    // 'Un mot gentil peut voyager loin et toucher des cœurs.',
  ];

  /// Tables Supabase.
  static const String usersTable = 'users';
  static const String messagesTable = 'messages';
  static const String deliveriesTable = 'deliveries';
}
